fix: Correct a type error in ForwardedDeviceProtocol
```
node_modules/buttplug/dist/main/src/server/managers/forwardeddevices/ForwardedDeviceProtocol.d.ts(18,5): error TS2416: Property 'ParseMessage' in type 'ForwardedDeviceProtocol' is not assignable to the same property in base type 'ButtplugDeviceProtocol'.
  Type '(aMsg: ButtplugDeviceMessage) => Promise<ButtplugMessage>' is not assignable to type '(aMsg: ButtplugMessage) => Promise<ButtplugMessage>'.
    Types of parameters 'aMsg' and 'aMsg' are incompatible.
      Property 'DeviceIndex' is missing in type 'ButtplugMessage' but required in type 'ButtplugDeviceMessage'.
```

This type mismatch causes issues when compiling the typescript to javascript.